version: "3.5"
services:
  app:
    container_name: lucaspiano-app
    image: dersonsena/lucas-piano-dev
    build:
      context: .docker
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
    networks:
      - lucaspiano-network

#  db:
#    container_name: lucaspiano-db
#    image: mysql:5.7
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    ports:
#      - 3306:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: secret
#      MYSQL_DATABASE: lucaspiano
#    volumes:
#      - ./.docker/data/mysql:/var/lib/mysql
#    networks:
#      - lucaspiano-network

networks:
  lucaspiano-network:
    driver: bridge