version: "3.5"
services:
  app:
    container_name: lucaspiano-app
    image: webdevops/php-nginx-dev:5.6
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/app
      - WEB_DOCUMENT_INDEX=index.php
      - PHP_MAX_EXECUTION_TIME=86400
    ports:
      - '8080:80'
    networks:
      - lucaspiano-network
    depends_on:
      - db

  db:
    container_name: lucaspiano-db
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp=false
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: lucaspiano
    volumes:
      - ./.docker/data/mysql:/var/lib/mysql
    networks:
      - lucaspiano-network

networks:
  lucaspiano-network:
    driver: bridge